# Main Page Title
title: "Sunil Boopalan"

# Your name
name: "Sunil Boopalan"

# Main section title
section: "Portfolio"

plugins:
 - "jekyll-github-metadata"

# Github repository
repository: sunilboopalan/SunilBoopalan.github.io

# Your job
work: "Cloud & Cybersecurity Engineer | Researcher | AI, Quantum Computing & Blockchain enthusiast."

# Section E-Mail link or anchor
section-email: "#contact"

# Description
description: "Sunil's personal website."

# Base url (Only dir eg. /blog | /portfolio)
baseurl: ""

# Link to the main page (or subpage)
url: "https://sunilboopalan.github.io"

# Contact E-Mail
email: "sunilboopalan3@gmail.com"

# Arc.io key
arc: ""

social-media:
 enabled: "true"
 github_username: "SunilBoopalan"
 discord: "https://discord.gg/tyRjenCys4"
 instagram: sunilb.io
 linkedin: "in/sunil-boopalan"
 

 projects:
  sort_by: stars # pushed / stars
  limit: 4
  exclude:
   archived: true
   forks: true
   projects:
    - "fest"

# Display svg decorations (boolean)
cards:
 enabled: "true"

# Extra link on navigation
blog: "https://www.shotok.in/"

# Title of the extra link
blog-title: "ShotOK"

# Support to mobile browsers (Itâ€™s unknown what range of browsers support this meta tags) [Better to set the value to "false"!] (Boolean)
mobile: "false"

# First Launch of the site
first-launch: "2022"

# Timezone
timezone: "America/Puerto_Rico"

# Encoding (default: utf-8)
encoding: utf-8

# Markdown and Default theme
markdown: kramdown
theme: minima

exclude: [vendor]

# Contact form
form:
 enabled: "true" # Display form on page (boolean)
 disabled: "true" # Disable the contact form inputs but don't hide the whole form. Enable this for eg. maintenance. (boolean)
 hide_html_form: "true" # Hide HTML form from page
 #action: "https://in.linkedin.com/in/sunil-boopalan?trk=profile-badge" # Form action, must support xhr requests (url)
 banner: "https://platform.linkedin.com/badges/js/profile.js" # Form banner (url)
 #banner_url: "https://in.linkedin.com/in/sunil-boopalan?trk=profile-badge" # Banner url (url)
 #action: "https://getform.io/f/f823ef85-b161-4cc1-9d60-ef2fb18b9276" # Form action, must support xhr requests (url)
 #banner: "https://lanyard.cnrad.dev/api/762316391491174403" # Form banner (url)
 #banner_url: "https://discord.com/users/762316391491174403" # Banner url (url)
 display_banner: "true" # Display form banner (boolean)

# Google Tracking ID
tracking_id: ""

# Google Site Verification ID
verification: ""

# Coding stats
wakatime:
 enabled: "true" # Boolean
 started: "2022" # Year when wakatime started moritoring your code activity
 link: "https://github.com/SunilBoopalan" # Your wakatime profile link
 embed: "https://github-readme-stats-2-smoky.vercel.app/api/top-langs/?username=SunilBoopalan&langs_count=8" # Coding stats embed image in .svg format (running in my vercel account)
 #OG embed: "https://github-readme-stats.vercel.app/api/top-langs/?username=SunilBoopalan&langs_count=8"





















